apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: your-docker-image:latest  # Replace with your actual Docker image
        ports:
        - containerPort: 8000  # Change if your app runs on a different port
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "messaging_app.settings"
kind: Service
metadata:
  name: django-app-service
spec:
  type: ClusterIP
  selector:
    app: django-app
  ports:
    - port: 8000  # Change if your app runs on a different port
      targetPort: 8000

   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: django-app
     labels:
       app: django-app
   spec:
     replicas: 3
     selector:
       matchLabels:
         app: django-app
     template:
       metadata:
         labels:
           app: django-app
       spec:
         containers:
         - name: django-app
           image: your-docker-image:latest  # Replace with your actual Docker image
           ports:
           - containerPort: 8000  # Change if your app runs on a different port
           env:
           - name: DJANGO_SETTINGS_MODULE
             value: "messaging_app.settings"
           - name: DATABASE_URL
             value: "postgres://user:password@localhost:5432/dbname"  # Example for a database URL
   ---
   apiVersion: v1
   kind: Service
   metadata:
     name: django-app-service
   spec:
     type: ClusterIP
     selector:
       app: django-app
     ports:
       - port: 8000  # Change if your app runs on a different port
         targetPort: 8000   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: django-app
     labels:
       app: django-app
   spec:
     replicas: 3
     selector:
       matchLabels:
         app: django-app
     template:
       metadata:
         labels:
           app: django-app
       spec:
         containers:
         - name: django-app
           image: your-docker-image:latest  # Replace with your actual Docker image
           ports:
           - containerPort: 8000  # Change if your app runs on a different port
           env:
           - name: DJANGO_SETTINGS_MODULE
             value: "messaging_app.settings"
           - name: DATABASE_URL
             value: "postgres://user:password@localhost:5432/dbname"  # Example for a database URL
   ---
   apiVersion: v1
   kind: Service
   metadata:
     name: django-app-service
   spec:
     type: ClusterIP
     selector:
       app: django-app
     ports:
       - port: 8000  # Change if your app runs on a different port
         targetPort: 8000
